springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  servlet:
    contextPath: /api

spring:
#  profiles:
#    active: local
  datasource:
    url: jdbc:h2:mem:schedulingDb
    #    url: jdbc:h2:file:/data/schedulingDb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        type: trace
#        SQL: debug
#        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

ex:
  app:
    jwtSecret: exrSecretKey
    jwtExpirationMs: 86400000
    jwtCookieName: exrScheduling